# Generated by Django 4.1 on 2022-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_myapp_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='age',
            field=models.BooleanField(default=0, verbose_name='Age'),
        ),
    ]
