# Generated by Django 4.1 on 2022-08-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_myapp_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
